name: AccentureWorkshop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  call-of-the-environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Call me by my $name"
      run: echo "I am $NAME"
    - name: "Call password"
      run: echo "${{secrets.PASSWORD}}"
      env:
        NAME: Tommy
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: typescript and css format check
        run: |
          npm run lint:ts
          npm run lint:css

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: npm ci, build and test
        run: |
          npm ci
          npm run build
          npm test
   
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      # build and deploy
      - name: Build
        run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
      # Step 2: Add deploy to Github pages here! Hot tip - The solution is in the Readme